version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: tpe-project-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: estudante
      POSTGRES_PASSWORD: ifsp
      POSTGRES_DB: test
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
